version: 2.1
orbs:
  node: circleci/node@1.1.6
  heroku: circleci/heroku@1.0.1

jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install --dev
            - run: npm run test
workflows:
    do_it:
      jobs:
        - build-and-test
        - heroku/deploy-via-git: # This is a pre-configured job.
            requires:
              - build-and-test
            filters:
              branches:
                only:
                  - master